# Generated by Django 5.0.1 on 2024-01-30 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=255, verbose_name='展示的昵称')),
                ('filename', models.CharField(default='', max_length=255, verbose_name='文件名称')),
                ('filepath', models.CharField(default='', max_length=255, verbose_name='文件路径')),
                ('size', models.IntegerField(default=0, verbose_name='大小')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('disabled', models.BooleanField(default=False, verbose_name='不可见')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Sorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('key', models.CharField(default='', max_length=255, verbose_name='key')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('photo', models.ManyToManyField(to='PhotoStore.photos')),
            ],
        ),
    ]
