# Generated by Django 5.0.1 on 2024-04-05 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=255)),
                ('job_name', models.CharField(default='', max_length=255)),
                ('job_id', models.IntegerField(default=0)),
                ('status', models.CharField(default='', max_length=10)),
                ('variables', models.JSONField(default=dict)),
                ('platform', models.CharField(default='', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('command', models.CharField(default='', max_length=255)),
                ('version', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
