# Generated by Django 3.2.13 on 2023-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='视频标题')),
                ('video_path', models.CharField(default='', max_length=255, verbose_name='视频路径')),
                ('cover_path', models.CharField(default='', max_length=255, verbose_name='封面路径')),
            ],
        ),
    ]
