# Generated by Django 5.0.1 on 2024-01-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(default='', max_length=255, verbose_name='文件路径')),
                ('qr_code_path', models.CharField(default='', max_length=255, verbose_name='二维码路径')),
                ('file_type', models.CharField(default='', max_length=255, verbose_name='文件类型')),
            ],
        ),
    ]
