# Generated by Django 3.2 on 2022-09-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_link', models.CharField(max_length=200, verbose_name='网站链接')),
                ('site_name', models.CharField(max_length=200, verbose_name='网站名称')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
            ],
        ),
    ]
