# Generated by Django 3.2.13 on 2024-10-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='助攻'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='死亡'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='doubleKills',
            field=models.IntegerField(default=0, verbose_name='双杀次数'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='kills',
            field=models.IntegerField(default=0, verbose_name='击杀'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='pentaKills',
            field=models.IntegerField(default=0, verbose_name='五杀'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='quadraKills',
            field=models.IntegerField(default=0, verbose_name='四杀次数'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='totalDamageDealtToChampions',
            field=models.IntegerField(default=0, verbose_name='对英雄造成伤害'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='totalDamageTaken',
            field=models.IntegerField(default=0, verbose_name='承受伤害'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='tripleKills',
            field=models.IntegerField(default=0, verbose_name='三杀次数'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='win',
            field=models.SmallIntegerField(default=0, verbose_name='赢否？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='summonerId',
            field=models.BigIntegerField(default=0),
        ),
    ]
